services:
  # PostgreSQL Database
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: dung_db
      POSTGRES_USER: dung_user
      POSTGRES_PASSWORD: dung_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Django Backend
  backend:
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://dung_user:dung_password@db:5432/dung_db
    depends_on:
      - db
    volumes:
      - ./backend:/app

  # React Frontend
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data: