# Generated by Django 4.2.7 on 2025-06-02 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_expenseshare_unique_together_expense_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='paid_by',
        ),
    ]
